#!/bin/bash


# wielki folder (ze spacja) na desktopie


if [ -z $1 ]; then
    echo "No arguments provided, usage: /where-fits [file names to check]" 
    exit
fi

f_size=0

IFS=$"\n"

for file in "$@"
do
    ((f_size += $(find "$file" -maxdepth 0 -exec du -shb '{}' \; | awk '{print $1+0}')))
done


echo -e "Size of those files: $f_size\n"

filesystems=$(df -B 1 | awk 'NR > 1 {print $6 " " $4}' | tail -n +2)


echo "Filesystems those files fit in: "

counter=0
while read -r f_info
do
    # ensure awk prints number, -lt for less than
    f_name=$(echo "$f_info" | awk '{print $1}')
    f_space=$(echo "$f_info" | awk '{print $2+0}')

    if [ $f_size -lt $f_space ]; then
        echo "Fits: $f_name with free: $f_space"
        ((counter++))
    fi


done <<< "$filesystems"

echo "Summary: fits in $counter filesystems"

