#!/bin/bash

path=/proc/sys/kernel/random

#echo "Press any key to exit program..."

while :
do
    avail=$(cat "$path/entropy_avail")
    pool=$(cat "$path/poolsize")
    printf "%s / %s\r" "$avail" "$pool"
    # use read 1 as one second delay
    read -s -r -n 1 -t 1 key
    if [ -n "$key" ] 
    then
        break
    fi
    

done



